language: python
sudo: false
branches:
  except:
    - gh-pages

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-asyncore MONOCLE_STACK=asyncore
    - python: 2.7
      env: TOXENV=py27-tornado MONOCLE_STACK=tornado
    - python: 2.7
      env: TOXENV=py27-twisted MONOCLE_STACK=twisted
  allow_failures:
    - python: 2.7
      env: TOXENV=py27-asyncore MONOCLE_STACK=asyncore

cache:
  - apt

addons:
  apt:
    packages:
      - libssl-dev

install:
  - pip install tox

script:
  - tox

after_success:
  - tox -e coveralls
  - tox -e lint
