language: python
sudo: false
branches:
  except:
    - gh-pages

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-asyncore MONOCLE_STACK=asyncore PYTHON_VERSION=27
    - python: 2.7
      env: TOXENV=py27-tornado MONOCLE_STACK=tornado PYTHON_VERSION=27
    - python: 2.7
      env: TOXENV=py27-twisted MONOCLE_STACK=twisted PYTHON_VERSION=27
    - python: 2.6
      env: TOXENV=py26-asyncore MONOCLE_STACK=asyncore PYTHON_VERSION=26
    - python: 2.6
      env: TOXENV=py26-tornado MONOCLE_STACK=tornado PYTHON_VERSION=26
    - python: 2.6
      env: TOXENV=py26-twisted26 MONOCLE_STACK=twisted PYTHON_VERSION=26
    - python: pypy
      env: TOXENV=pypy-tornado MONOCLE_STACK=tornado PYTHON_VERSION=26
  allow_failures:
    - python: 2.7
      env: TOXENV=py27-asyncore MONOCLE_STACK=asyncore PYTHON_VERSION=27
    - python: 2.6
      env: TOXENV=py26-asyncore MONOCLE_STACK=asyncore PYTHON_VERSION=26

cache:
  - apt

addons:
  apt:
    packages:
      - libssl-dev

install:
  - pip install tox

script:
  - tox

after_success:
  - source .tox/py${PYTHON_VERSION}-${MONOCLE_STACK}/bin/activate && py.test -q --confcutdir=.. -n 1 --junitxml=tests/junit.xml --cov-report xml --cov monocle --cov-report=html --cov-report term-missing --pep8
  - source .tox/py27-${MONOCLE_STACK}/bin/activate && pylint monocle

