language: python
sudo: false
branches:
  except:
    - gh-pages

matrix:
  include:
    - python: 2.7
      env: TOXENV=asyncore MONOCLE_STACK=asyncore
    - python: 2.7
      env: TOXENV=coverage MONOCLE_STACK=twisted
    - python: 2.7
      env: TOXENV=tornado MONOCLE_STACK=tornado
    - python: 2.7
      env: TOXENV=twisted MONOCLE_STACK=twisted
  allow_failures:
    - python: 2.7
      env: TOXENV=asyncore MONOCLE_STACK=asyncore
    - python: 2.7
      env: TOXENV=coverage MONOCLE_STACK=twisted

cache:
  - apt

addons:
  apt:
    packages:
      - libssl-dev

install:
  - pip install tox

script:
  - tox
